# -*- coding: utf-8 -*-
"""00-NumPy-Arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zg6AMMk_WVu9TlhTq33u_PL9NsF4hXk6

# Numpy Crash Course
"""

import numpy as np

"""## Creating Arrays"""

my_list = [0,1,2,3,4]

arr = np.array(my_list)

print(arr)

np.arange(0,10)

np.arange(0,10,2)

np.zeros((5,5))

np.ones((2,4))

"""## Operations"""

np.random.seed(101) # watch video for details
arr = np.random.randint(0,100,10)

print(arr)

arr2 = np.random.randint(0,100,10)

print(arr2)

print(arr.max())

print(arr.min())

print(arr.mean())

print(arr.argmin())

print(arr.argmax())

print(arr.reshape(2,5))

"""## Indexing"""

mat = np.arange(0,100).reshape(10,10)

print(mat)

row = 0
col = 1

print(mat[row,col])

# With Slices
print(mat[:,col])

print(mat[row,:])

print(mat[0:3,0:3])

"""# Great Job!"""