# -*- coding: utf-8 -*-
"""01-Images-and-NumPy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ibbPL3yaj9wmDdJRLFfp77-w3GnwMMEO

# Images and Numpy

Numpy can read in certain files types, this includes images stored as arrays. In this quick lecture, we'll quickly cover how you can work with images in NumPy. **Keep in mind, we will mainly be using OpenCV to open and view images, but later on in the Deep Learning Section we will come back to NumPy and Matplotlib. **
"""

import numpy as np

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

from PIL import Image

pic = Image.open('00-puppy.jpg')

pic

type(pic)

pic_arr = np.asarray(pic)
pic_arr.shape

#plt.imshow(pic_arr)

pic_red = pic_arr.copy()

pic_red[:, :, 1] = 0    # Zero out contribution from green
pic_red[:, :, 2] = 0    # Zero out contribution from blue

plt.imshow(pic_red)
plt.savefig('plot.png')
"""# Great Job!"""